# Generated by Django 5.1.5 on 2025-03-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
