# Generated by Django 5.1.5 on 2025-03-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categoty_text',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
