# Generated by Django 5.1.5 on 2025-03-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_categoty_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categoty_text',
        ),
    ]
